### PR TITLE
Add a DivRem trait and implement it for Int

### PR DESCRIPTION
**Pull request by habnabit**
>This means that `divrem` can be done more efficiently for `(Int, usize)` -> `(Int, usize)` than having to round-trip through an `Int`.

>Probably a few more impls of `DivRem` are required, but this is a base to work from at least.

### CODE REVIEW

**Comment by habnabit** [comment]
Rebased onto 15076282c40f64e6f9fea6de770d8d8a4c5e9e8a.

**Comment by Aatch** [comment]
Failing to compile, not entirely sure why, possibly a bug in `associated_type_defaults`.

**Comment by habnabit** [comment]
Well it doesn't fail anymore if you don't have a default associated type. I guess I'll try to figure out why.

**Comment by habnabit** [comment]
Rebased again onto bb43d4ed8ad698cb6693d6da6fa55d86dcc3985a, removing the associated type default. They're hella buggy, it seems.

**Pull request merged**
