### PR TITLE
update iter::Step impl

### PR DESCRIPTION
**Pull request by arthurprs**
Compiles on nightly as of today.

### CODE REVIEW

**Comment by zcdziura** [comment]
I think Travis' configuration may be a little out-of-date. I just cloned this repository and branch, and ran all of the tests on my machine. All tests passed.

**Comment by arthurprs** [comment]
I'll try to re trigger travis.

**Comment by arthurprs** [comment]
It's passing now :)

**Comment by Aatch** [comment]
Awesome, thanks!

**Pull request merged**
