### PR TITLE
WIP Fixing software limb div

### PR DESCRIPTION
**Pull request by kali**
Hello there,

I'm trying to fix the software divisor (and possibly add more assembly ones after that). I've implemented some `quickchecks` for the four basics operators, and made a `--features fallbacks` to enable to force the software operators.

This could be merged, if you feel like it, but I think I'm just getting started:

I can confirm what we already knew from people experimenting on ARM, it looks like there is a bug in the software divisor ( `ll::limb::div(hn,ln,d) -> (q,r)` ). The code is a bit... frightening. Can somebody point me to any place where we have a description of how it works ? or possibly the implementation it was ported from to get started ?

### CODE REVIEW

**Comment by Aatch** [comment]
If you could make the fallback stuff a separate PR, that'd be great.

**Comment by kali** [comment]
Sure! Glad to see you're still around. See PR #79 with the callback related stuff.

How do you feel about the cross-compiling stuff ? I can clean it up a bit and put it in a separate PR if you're interested.

**Comment by Aatch** [comment]
The cross-compiling stuff looks ok. In the long-run I'd probably want to be not using `num`, but using it is fine for now. Having that be a separate PR would be good too.

**Comment by kali** [comment]
All right, I'll put the cross-compiling effort in a separate PR, and will probably make a third one with the warnings and lazy build fixes.

About num, yeah, I don't have much love for it (hence my interest in ramp). On the top of my head, I think the table generation in build.rs can be made to work for all targets just by using the u64 ops. But num comes in handy to cross-compile tests for alternative platforms (like phones) without having to cross compile GMP. Num being pure rust is much easier to deal with, and only correctess is at stake.

**Comment by kali** [comment]
hey @Aatch, any chance we could move this and #80 forward towards a release ?

**Comment by Aatch** [comment]
I merged #80, which is probably the source of the conflict.

**Comment by kali** [comment]
I think we can just close this one, #79 and #80 were the interesting stuff.

**Pull request closed without merging**
