### PR TITLE
Use RawVec for `Int`s memory management.

### PR DESCRIPTION
**Pull request by huonw**
This abstracts out handling the allocator with alignment/sizes etc, and
has most interesting operations predefined.

### CODE REVIEW

**Comment by huonw** [comment]
The use of `reserve` rather than `reserve_exact` means things can be a little over-allocated, but this isn't necessarily wrong?

**Comment by Aatch** [comment]
It looks like `reserve` allocates for double the space you actually ask for. As the only operation to grow the size rapidly is multiplication, and that needs a separate allocation anyway, I'd rather not over-allocate quite so much.

**Comment by huonw** [comment]
Ok, switched to `reserve_exact`.

**Comment by Aatch** [comment]
Sweet!

**Pull request merged**
