### PR TITLE
Fix compiler warnings about SipHasher and left/right overflowing shifts

### PR DESCRIPTION
**Pull request by doomrobo**

### CODE REVIEW

**Comment by arthurprs** [comment]
This is great! Travis doesn't look happy though.

**Comment by doomrobo** [comment]
Hmm, I can't reproduce these on my x86_64 linux box. Also the errors are different on the two builds that give errors. What do you think the issue could be?

**Comment by arthurprs** [comment]
Are you sing the same flags as travis? Also, could you try to trigger a rebuild by travis?

**Comment by doomrobo** [comment]
I am, and the builds that are failing are using no feature flags. I think you can trigger a rebuild as the owner, but I'll just close and reopen the PR and see if that does it.

**Comment by doomrobo** [comment]
That didn't work. Looks like quickcheck_macros is actually broken

**Comment by andersk** [comment]
I sent a quickcheck_macros fix to BurntSushi/quickcheck#153.

**Comment by andersk** [comment]
You can rebase this onto #85 for passing Travis tests.

**Comment by doomrobo** [comment]
There are no longer any overflowing warnings. I'll just submit a new PR for the SipHasher warnings.

**Pull request closed without merging**
