### PR TITLE
Feature random int generation

### PR DESCRIPTION
**Pull request by kunerd**

### CODE REVIEW

**Comment by Aatch** [comment]
Awesome, do you mind adding some documentation? Doesn't need much, just a brief explanation for each function. Also a short example on the trait itself would be nice, as usage isn't immediately obvious. (Took me a moment to work out what was going on).

**Comment by kunerd** [comment]
Adding some documentation is no problem. I think there also should be a `gen_int_range` function, like in nums BigInt. Should I replace the calls of the `rand_int` function from test module with the new `gen_int` function?

**Comment by Aatch** [comment]
>Should I replace the calls of the rand_int function from test module with the new gen_int function?

Yeah, sounds like a good idea.

**Comment by Aatch** [comment]
Awesome, looks good, thanks!

**Pull request merged**
